@setfilename openbsdfaq.info
@synindex tp fn
@set _body_tags BGCOLOR="#FFFFFF" TEXT="#000000" LINK="#23238E"
@settitle @strong{OpenBSD} Frequently Asked Questions
@setchapternewpage off
@ifinfo
@format
START-INFO-DIR-ENTRY
* openbsdfaq: (openbsdfaq).               @strong{OpenBSD} documenatation.
END-INFO-DIR-ENTRY
@end format
@end ifinfo
@titlepage
@sp 10
@center @titlefont{@strong{OpenBSD} Frequently Asked Questions}
@sp 10
@center Copyright @copyright{} Copyright 1998 Theo de Raadt
@end titlepage

@node Top, Introduction, (dir), (dir)
@ifinfo
This document contains frequently asked questions about the @strong{OpenBSD}
operating system.  It is required reading for @strong{OpenBSD} users.  The
people who maintain and support @strong{OpenBSD} will generally not answer
questions or respond to bug reports that are documented here.
@end ifinfo

@menu
* Introduction::		About @strong{OpenBSD} and this FAQ.
* Resources::			@strong{OpenBSD} information resources.
* Buying::			How to buy an @strong{OpenBSD} CD.
* Installing::			@strong{OpenBSD} installation tips.
* Source::			Obtaining @strong{OpenBSD} source code.
* Kernels::			Building new kernels.
* Rebuilding::			Rebuilding @strong{OpenBSD} from source.
* Networking::			Network configuration tips.
* Disks::			Configuring disks for use with @strong{OpenBSD}.
* I386::			Configuration specific to the i386 port.
* Software:			Obtaining ported software for @strong{OpenBSD}.
@end menu

@cindex General Information
@node Information, Questions, Top, Top
@chapter About @strong{OpenBSD} and this FAQ.

@menu
* About::			What is @strong{OpenBSD}?
* Free::			Is it really free?
* Why::				Why might I want to use @strong{OpenBSD}?
* Platforms::			What platforms are supported?
* Support::			How can I help support @strong{OpenBSD}?
* Who-OpenBSD::			Who maintains @strong{OpenBSD}?
* Who-FAQ::			Who maintains this FAQ?
@end menu

@cindex About OpenBSD
@node About, Free, Introduction, Introduction
@section What is @strong{OpenBSD}?

The @strong{OpenBSD} project produces a freely available, multi-platform
4.4BSD-based UNIX-like operating system. Our efforts place emphasis
on portability, standardization, correctness, and security.
@strong{OpenBSD} supports binary emulation of most binaries from
SVR4 (Solaris), FreeBSD, Linux, BSDI, SunOS, and HPUX.

More about the project goals: @uref{http://www.openbsd.org/goals.html,
http://www.openbsd.org/goals.html}.

@cindex Free
@node Free, Why, About, Introduction
@section Is it really free?

@strong{OpenBSD} is all free.  The binaries are free.  The source is
free.  All parts of @strong{OpenBSD} have reasonable copyright terms
permitting free redistribution.

More about copyright policy:  @uref{http://www.openbsd.org/policy.html,
http://www.openbsd.org/policy.html}.

The maintainers of @strong{OpenBSD} support the project largely
from their own pockets.  This includes the time spent programming
for the project, equipment used to support the many ports, the
network resources used to distribute @strong{OpenBSD} to you, and
the time spent answering questions and investigating users' bug
reports. The @strong{OpenBSD} developers are not independently
wealthy and even small contributions of time, equipment, and
resources make a big difference.

@xref{Support}

@cindex Why
@node Why, Platforms, Free, Introduction
@section Why might I want to use @strong{OpenBSD}?

New users frequently want to know whether @strong{OpenBSD} is
superior to some other free Unix-like operating system.  That
question is largely un-answerable and is the subject of countless
(and useless) religious debates.  @strong{Do not, under any
circumstances, ask such a question on an OpenBSD mailing list.}

Below are some reasons why we think @strong{OpenBSD} is a
useful operating system.  Whether @strong{OpenBSD} is right for
you is a question that only you can answer.

@itemize @bullet
@item
@strong{OpenBSD} runs on many different hardware platforms.
@item
@strong{OpenBSD} developers have spent countless hours in a focused
effort to systematically eliminate security holes (and potential security
holes) from the code.
@item
@strong{OpenBSD} is a full-featured Unix-like operating system
available in source form at no charge.
@item
@strong{OpenBSD} integrates cutting-edge security technology suitable
for building firewalls and private network services in a distributed
environment.
@item
@strong{OpenBSD} benefits from strong on-going development in many areas,
offering opportunities to work with emerging technologies with an
international community of programmers and end-users.
@item
@strong{OpenBSD} offers opportunities for ordinary people to participate
in the development and testing of the product.
@end itemize

@cindex Platforms
@node Platforms, Support, Why, Introduction
@section What platforms are supported?

Information about supported hardware platforms and peripherals
can be found on the platforms web page: @uref{http://www.openbsd.org/plat.html,
http://www.openbsd.org/plat.html}.

More specific information is sometimes available from the port maintainers.
Read the platforms web page first.

Support for specific platforms and peripherals often changes rapidly.
If your equipment is not supported in the latest full release, you
may find success in the current source or snapshot for your platform.

@cindex Support
@node Support, Who-OpenBSD, Platforms, Introduction
@section How can I help support @strong{OpenBSD}?

We are greatly indebted to the people and organizations that have
contributed to the @strong{OpenBSD} project.  They are acknowledged
by name here: @uref{http://www.openbsd.org/donations.html,
http://www.openbsd.org/donations.html}.

@strong{OpenBSD} has a constant need for several types of
support from the user community.  If you find @strong{OpenBSD} useful,
you are strongly encouraged to find a way to contribute.  If none
of the suggestions below are right for you, feel free to propose an
alternative by sending e-mail to @email{donations@@openbsd.org}.

@itemize @bullet
@item
Buy an @strong{OpenBSD} CD.  Includes the current full release of
@strong{OpenBSD}, and is bootable on many platforms.   Generates
revenue to support the @strong{OpenBSD} project, and reduces the
strain on network resources used to deliver the distribution via
the Internet.  This inexpensive two-CD set includes full source.
Remember, your friends need their own copy!
@item
Donate money.  The project has a constant need for cash to pay for
equipment, network connectivity, and expenses relating to CD publishing.
Manufacturing CDs requires an up-front out-of-pocket investment for
the @strong{OpenBSD} developers, without guaranteed return.  Send
e-mail to @email{donations@@openbsd.org} to find out how to contribute.
Even small donations make a profound difference.
@item
Donate equipment and parts.  The project has a constant need for
general and specific hardware.  Items such as IDE and SCSI disks,
and various types of RAM are always welcome.  For other types of
hardware such as computer systems and motherboards, you should
inquire as to current need.  Write to @email{donations@@openbsd.org}
to arrange for shipment.
@item
Donate your time and skills.  Programmers who enjoy writing operating
systems are naturally always welcome, but there are literally dozens
of other ways that people can be useful.  Follow mailing lists and
help answer new-user questions.  Help maintain documentation by submitting
new FAQ material (to @email{faq@@openbsd.org}).  Form a local user
group and get your friends hooked on @strong{OpenBSD}.  Make a case
to your employer for using @strong{OpenBSD} at work.  If you're a
student, talk to your professors about using @strong{OpenBSD} as
a learning tool for Computer Science or Engineering courses.
@end itemize

It's also worth mentioning one of the most important ways you
@emph{should not} try to "help" the @strong{OpenBSD} project:
do not waste your time engaging in operating system flame wars
on Usenet newsgroups.  It does nothing to help the project
find new users, and it can cause substantial harm to important
relationships that @strong{OpenBSD} developers have with other
operating system developers.  The @strong{OpenBSD} team uses, learns
from, and respects many different operating systems and does
not presume to dictate what others should use.

@cindex Who-OpenBSD
@node Who-OpenBSD, Who-FAQ, Support, Introduction
@section Who maintains @strong{OpenBSD}?

@strong{OpenBSD} is maintained by a development team spread across
many different countries.  The project is coordinated by
Theo de Raadt, located in Canada.

@cindex Who-FAQ
@node Who-FAQ,  , Who-OpenBSD, Introduction
@section Who maintains this FAQ?

Paul Southworth and Jonathan Katz maintain the @strong{OpenBSD}
FAQ, with contributions from dozens of helpful people.

The FAQ maintainers can be reached at @email{faq@@openbsd.org}.

The FAQ is written in @TeX{}Info and converted to other formats.
Contributors are welcome to send their suggestions and additions
as ASCII text, or as context diffs to the current @TeX{}Info version,
found here: @uref{http://www.openbsd.org/faq/openbsdfaq.texi,
http://www.openbsd.org/faq/openbsdfaq.texi}

Available versions of the FAQ are:

@itemize @bullet
@item
HTML
@uref{openbsdfaq_toc.html, openbsdfaq_toc.html}
@item
@TeX{}Info
@uref{openbsdfaq.texi, openbsdfaq.texi}
@item
ASCII Text
@uref{openbsdfaq.txt, openbsdfaq.txt}
@item
PostScript
@uref{openbsdfaq.ps, openbsdfaq.ps}
@end itemize

@bye
